### ISSUE TITLE
Why validation-loss is -nan?

### ISSUE THREAD

**Issue by gom7745** [bingzhengwei/ftrl_proximal_lr#13]
The instance is like this
```
-1 8111:2.9488658905029297 11507:1.0 13082:1.0 13178:1.0 16133:1.0 22000:1.0 22888:1.0 28221:1.0 36004:1.0 36542:1.0 37596:1.0 38549:1.0 48206:1.0 48786:1.0 56133:1.0 56694:1.0 58444:
1.0 59045:1.0 80219:1.0 83143:1.0 83336:1.0 85436:1.0 90750:2.9488658905029297 109126:1.0 109126:1.0 110542:1.0 111070:1.0 113837:1.0 116355:1.0 119025:1.0 124098:1.0 128976:1.0 129492:1.0 1299
54:1.0 134077:1.0 137757:1.0 138089:1.0 139260:1.0 140558:1.0 142435:1.0 144453:1.0 146199:2.9488658905029297 148378:1.0 148690:1.0 151094:1.0 162239:1.0 163439:1.0 167017:1.0 170853:1.0 171369
:1.0 171885:1.0 172801:1.0 176027:1.0 177852:2.9488658905029297 180997:1.0 181929:1.0 181946:1.0 183749:1.0 186802:1.0 190239:1.0 190705:1.0 197947:1.0 203165:1.0 206100:1.0 210524:1.0 214260:1
.0 221477:1.0 233497:1.0 234544:1.0 236809:1.0 237575:1.0 251918:1.0 262375:1.0 263600:1.0 267415:1.0 268116:1.0 275559:1.0 275898:1.0 276946:1.0 277961:1.0 281753:1.0 283133:1.0 285053:1.0 286
215:1.0 291402:1.0 522376:1.0 2209491:1.0 2340160:1.0
.
``` 

And I use this command ` ./ftrl_proximal_lr/ftrl_train -f  mergedTraining.txt -m trainModel2 -t mergedValidation.txt `, but the validatio-loss is always -nan.

Could you please figure out the mistake I made?

Also, when I add `--double`, segmentation fault occurred.

I find that the function `GetWeight` returns a -nan weight and the idx was 2340160 which exceeds the max idx (i.e. 2209010) in the trainModel2.

Many thanks.

**Comment by gom7745** [comment]
It seems that n_[idx] is overflowed.
The result I get today is different from the one I got yesterday.
The instance number becomes 14213095 rather than 14215573 (yesterday).
The idx becomes 2341275 rather than 2341275 (yesterday).

Do you have any idea?

**Comment by bingzhengwei** [comment]
I've fixed this by adding a sanity check of idx. Could you try again?

**Comment by gom7745** [comment]
Problem solved. Thanks!
