### ISSUE TITLE
start from error

### ISSUE THREAD

**Issue by HyperGroups** [bingzhengwei/ftrl_proximal_lr#14]
when set parameter: start-from
then the parameters like alpha lose its function, 
and was set to be -0.21

**Comment by bingzhengwei** [comment]
Please make sure the input of --start-from parameter is ".save" model file. There will be two model files after training, one is the actual model, another one with ".save" suffix is for start-from param in the next round.

**Comment by HyperGroups** [comment]
OK, got is, thanks.
